model:
  target: models.score_matching.Diffusion2D_NS
  params:
    lr: 1e-4
    unet_config:
      target: models.unets.PFGMPPUNet
      params:
        dim: 128
        in_channels: 4
        out_channels: 4
        cond_size: 0
        kernel_size: 3
        padding: 1
        model_channels: 32
        channel_mult: [1, 2, 2, 2]
        channel_mult_emb: 2
        num_blocks: 1
        dropout: 0.0
        dim_mult_time: 1
        cond_drop_prob: 1
        adaptive_scale: True
        skip_scale: 1
        groups: 8
        pfgmpp: True
        D: 2048
        use_fp16: False
        sigma_min: 0
        sigma_max: 1e10
        sigma_data: 0.5
        model_type: 'CFGUNet'
    loss_fn_config:
      target: models.pfgmpp.EDMLoss
      params:
        P_mean: -1.2
        P_std: 1.2
        sigma_data: 0.5
        gamma: 5
        D: 2048
        N: 65536
    sampler_config:
      target: models.pfgmpp.EDM_Sampler
      params:
        num_steps: 18
        sigma_min: 0.002
        sigma_max: 80
        rho: 7
        S_churn: 0
        S_min: 0
        S_max: 1e10
        S_noise: 0
        pfgmpp: True
    residual_config:
      target: physics.flux.FluxCalculator
      params:
        Nx: 128
        Ny: 128
        Nz: 1
        L: 1
        pad_width: 2
        mode: 'periodic'
        gamma: 1.6666666666666667

data:
  target: dataloaders.loaders.PDEBench2D_Dataloader
  params:
    saved_folder: '/mnt/14ec0bc1-61ef-47a7-b0b0-623f4a658402/csjacobs/data/2D_incomp_navier_stokes/2D/CFD/2D_Train_Rand/'
    file_name: '2D_CFD_Rand_M1.0_Eta0.1_Zeta0.1_periodic_128_Train.hdf5'
    batch_size: 128
    num_workers: 8
    train_type: 'single'
    t_train: 21

lightning:
  lock_base: False
  trainer:
    accelerator: gpu
    strategy: ddp_find_unused_parameters_true
    devices: 0
    precision: 16-mixed
  epochs: 2000
  save_every_n_epochs: 5
  sample_every_n_steps: 2000
