model:
  target: models.score_matching.DiffusionSDE
  params:
    lr: 1e-4
    unet_config:
      target: models.unets.UNET1
      params:
        in_channels: 1
        n_feat: 256
        pool_size: 8
        data_size: 256
        cond_size: 1
    sde_config:
      target: sdes.forward.VP
      params:
        beta_min: 1e-4
        beta_max: 10
    sampler_config:
      target: sdes.backward.EulerMaruyama
      params:
        num_time_steps: 1000
        eps: 1e-5

data:
  target: dataloaders.loaders.BurgersLoader
  params:
    data_dir: /home/csjacobs/git/diffusionPDE/datasets/Burgers1D/Nu0.01_256
    batch_size: 24
    num_workers: 8

lightning:
  trainer:
    accelerator: gpu
    strategy: ddp
    devices: 1,2,3
    precision: 16-mixed
  epochs: 5000
  save_every_n_epochs: 2
  sample_every_n_steps: 2500
