model:
  target: models.score_matching.DiffusionSDE
  params:
    lr: 1e-4
    unet_config:
      target: models.unets.UNET1
      params:
        in_channels: 2
        n_feat: 256
        pool_size: 4
        data_size: 64
        cond_size: 16
        controlnet:
          use: True
          condition_encoder:
            target: models.unets.CondVec2Img
            params:
              cond_size: 16
              data_size: 64
              channels: 2
    sde_config:
      target: sdes.forward.VP
      params:
        beta_min: 1e-4
        beta_max: 10
    sampler_config:
      target: sdes.backward.ProbabilityFlowODE
      params:
        num_time_steps: 2000
        eps: 1e-5
    residual_config:
      target: physics.operators.DarcyFlow
      params:
        dx: 0.015625
        eps: 1e-8
        mu_p: 0.0
        sigma_p: 0.08232874
        mu_k: 1.14906847
        sigma_k: 7.81547992

data:
  target: dataloaders.loaders.DarcyLoader
  params:
    data_dir: /home/csjacobs/git/diffusionPDE/datasets/Darcy_n16
    batch_size: 128
    num_workers: 8

lightning:
  lock_base: True
  trainer:
    accelerator: gpu
    strategy: ddp
    devices: 2,3
    precision: 16-mixed
  epochs: 5000
  save_every_n_epochs: 5
  sample_every_n_steps: 2000
