model:
  target: models.score_matching.DiffusionSDE
  params:
    lr: 1e-4
    unet_config:
      target: models.unets.CFGUNet
      params:
        data_size: 64
        in_channels: 2
        out_channels: 2
        cond_size: 16
        kernel_size: 3
        padding: 1
        model_channels: 256
        channel_mult: [1, 2]
        channel_mult_emb: 2
        num_blocks: 1
        dropout: 0.0
        dim_mult_time: 1
        cond_drop_prob: 0.0
        adaptive_scale: True
        skip_scale: 1
    sde_config:
      target: sdes.forward.VP
      params:
        beta_min: 1e-4
        beta_max: 10
    sampler_config:
      target: sdes.backward.ProbabilityFlowODE
      params:
        num_time_steps: 2000
        eps: 1e-5
    residual_config:
      target: physics.operators.DarcyFlow
      params:
        dx: 0.015625
        eps: 1e-8
        mu_p: 0.0
        sigma_p: 0.08232874
        mu_k: 1.14906847
        sigma_k: 7.81547992

data:
  target: dataloaders.loaders.DarcyLoader
  params:
    data_dir: /home/csjacobs/git/diffusionPDE/datasets/Darcy_n16
    batch_size: 128
    num_workers: 8

lightning:
  lock_base: False
  trainer:
    accelerator: gpu
    strategy: ddp_find_unused_parameters_true
    devices: 0,1
    precision: 16-mixed
  epochs: 5000
  save_every_n_epochs: 5
  sample_every_n_steps: 2000
